Notes
vokecodes/Dropp pull request #90
Opened 2024-11-21 14:32 UTC by nonso-uj

2024-11-21 14:44 UTC, vokecodes requested changes

2024-11-21 14:47 UTC, nonso-uj commented on src/pages/chef/ChefDineIn.tsx
> +import InfiniteScroll from "react-infinite-scroll-component";
Oh, thought it was a typo, the glitch stopped when I changed it, I'll change it back

2024-11-21 14:59 UTC, vokecodes commented on src/pages/chef/ChefDineIn.tsx
> +import InfiniteScroll from "react-infinite-scroll-component";
No, fix with the component use

2024-11-23 07:23 UTC, vokecodes requested changes

2024-11-23 07:23 UTC, vokecodes commented on src/pages/chef/Kitchen.tsx
> -          dataLength={restaurantOrders?.length} // This is important to track the length of your data array
@nonso-uj Make us of the component InfinityScroll

2024-11-23 15:46 UTC, vokecodes requested changes

2024-11-23 15:46 UTC, vokecodes commented on src/pages/chef/Kitchen.tsx
> -          dataLength={restaurantOrders?.length} // This is important to track the length of your data array
@nonso-uj I can still see it here

2024-11-23 16:53 UTC, vokecodes commented
@nonso-uj There are conflicts

2024-11-23 17:09 UTC, merged